paths:
  static: ''
  uploads: uploads
timezone: America/Toronto
markdown:
  engine: commonmark
  options: {}
collections_config:
  pages:
    path: ''
    icon: wysiwyg
  data:
    path: data
    icon: data_usage
