name = "pinpoint-proxy"
main = "pinpoint-proxy.js"
compatibility_date = "2026-09-22"
account_id = "00ae76e7cc375a8175a3dde4f2a48ec0"

routes = [
  { pattern = "williamguindon.me/api/pinpoint-proxy*", zone_name = "williamguindon.me" }
]
